const players = [
  {
    firstName: "Jalen",
    lastName: "Brunson",
    position: "PG",
    age: 28,
    photo: "imgs/jalenbrunson.png",
  },
  {
    firstName: "Josh",
    lastName: "Hart",
    position: "SG",
    age: 29,
    photo: "imgs/joshhart.png",
  },
  {
    firstName: "OG",
    lastName: "Anunoby",
    position: "SF",
    age: 27,
    photo: "imgs/ogananoby.png",
  },
  {
    firstName: "Mikal",
    lastName: "Bridges",
    position: "SF",
    age: 28,
    photo: "imgs/mikalbridges.png",
  },
  {
    firstName: "Karl-Anthony",
    lastName: "Towns",
    position: "C",
    age: 29,
    photo: "imgs/karlanthonytowns.png",
  },
  {
    firstName: "Precious",
    lastName: "Achiuwa",
    position: "PF",
    age: 25,
    photo: "imgs/preciousachewa.png",
  },
  {
    firstName: "Miles",
    lastName: "McBride",
    position: "PG",
    age: 24,
    photo: "imgs/milesmcbride.png",
  },
  {
    firstName: "Cameron",
    lastName: "Payne",
    position: "PG",
    age: 30,
    photo: "imgs/cameronpayne.png",
  },
  {
    firstName: "Delon",
    lastName: "Wright",
    position: "PG",
    age: 33,
    photo: "imgs/delonwright.png",
  },
  {
    firstName: "Mitchell",
    lastName: "Robinson",
    position: "C",
    age: 26,
    photo: "imgs/mitchellrob.png",
  },
  {
    firstName: "Landry",
    lastName: "Shamet",
    position: "SG",
    age: 27,
    photo: "imgs/landryshamet.png",
  },
  {
    firstName: "Tyler",
    lastName: "Kolek",
    position: "PG",
    age: 23,
    photo: "imgs/tylerkolek.png",
  },
  {
    firstName: "Pacome",
    lastName: "Dadiet",
    position: "SG",
    age: 19,
    photo: "imgs/pacomedeidet.png",
  },
  {
    firstName: "Kevin",
    lastName: "McCullar Jr.",
    position: "SF",
    age: 23,
    photo: "imgs/kevinmccular.png",
  },
  {
    firstName: "Ariel",
    lastName: "Hukporti",
    position: "C",
    age: 22,
    photo: "imgs/arielhukporti.png",
  },
  {
    firstName: "Anton",
    lastName: "Watson",
    position: "SF",
    age: 24,
    photo: "imgs/antonwatson.png",
  },
  {
    firstName: "Marjon",
    lastName: "Beauchamp",
    position: "SF",
    age: 24,
    photo: "imgs/marjonbeauchamp.png",
  },
  {
    firstName: "P.J.",
    lastName: "Tucker",
    position: "PF",
    age: 40,
    photo: "imgs/pjtucker.png",
  },
];
